version: '3.8'

services:
  web:
    build:
      context: .
    container_name: icm-web
    ports:
      - "8080:80"
    volumes:
      - ./var/www/html
    networks:
      - icm-net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: icm-jenkins
    ports:
      - "8081:8080"  # Jenkins UI
      - "50000:50000" # agents
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - icm-net

volumes:
  jenkins_home:

networks:
  icm-net:
